ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :memo:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Компиляция программ на языке C
Vladimir Kutuev <vladimir.kutuev@gmail.com>
:source-highlighter: rouge
:rouge-style: github
:icons: font
:sectnums:

== Волшебная кнопка Build

== Волшебный `gcc`

Рассмотрим простой пример программы, разделённой на два файла с исходным кодом.

.`prog.c`
[source,c]
----
#include <stdio.h>

unsigned int fact(unsigned int n);

int main() {
	printf("%u\n", fact(5));
	return 0;
}
----

.`func.c`
[source,c]
----
unsigned int fact(unsigned int n) {
	unsigned int acc = 1;
	for (; n > 0; --n) {
		acc *= n;
	}
	return acc;
}
----

Выполняем `gcc func.c prog.c`, получаем исполняемый файл `a.out`.
Давайте изучим, как `gcc` это проделывает.

Вот наши файлы с исходным кодом.
// Тут 1-я картинка

Попросим `gcc` быть поразговорчивее.

[source,shell]
----
prog.c func.c -v
----

[TIP]
====
У многих программ есть опция командной строки для более подробного вывода.
Чаще всего это флаги `-v` или `--verbose`.

Также бывают утилиты, позволяющие ещё повысить подробность вывода раз, часто это сделано следующим образом: `-v`, `-vv`, `-vvv` и так далее.
====

Смотрим на вывод `gcc`.
И сначала мы видим информацию о самом `gcc`.

----
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.2.1 20240910 (GCC)
----

Тут мы видим:

* версию тулчейна;
* платформу, под которую производится компиляция;
* опции, с которыми gcc был сконфигурирован;
* и другая информация.

=== Компиляция

Дальше мы увидим вызов компилятора языка C -- утилиты `cc1`.

----
COLLECT_GCC_OPTIONS='-v' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a-'
  /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/cc1 -quiet -v prog.c -quiet -dumpdir a- -dumpbase prog.c -dumpbase-ext .c -mtune=generic -march=x86-64 -version -o /tmp/cc8EU5kU.s

GNU C17 (GCC) version 14.2.1 20240910 (x86_64-pc-linux-gnu)
	compiled by GNU C version 14.2.1 20240910, GMP version 6.3.0, MPFR version 4.2.1, MPC version 1.3.1, isl version isl-0.27-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/include
 /usr/local/include
 /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/include-fixed
 /usr/include
End of search list.
Compiler executable checksum: 91e980a230f7d2e39f93577991713edd
----

Результатом её работы будет файл на языке ассемблера (`-o /tmp/cc8EU5kU.s`).

// Тут 2-я картинка

Важно отметить, что компиляция тоже состоит из нескольких шагов:

* препроцессинг;
* лексический анализ;
* синтаксический анализ;
* семантический анализ;
* оптимизация;
* кодогенерация.

==== Препроцессинг

// [NOTE]
// .Немного исторического контекста
// ====
// Раньше этот шаг выполнялся отдельной утилитой `cpp` (C preprocessor, а не {cpp})
// ====


На этом шаге выполняются макроподстановки, обрабатываются https://en.wikipedia.org/wiki/Digraphs_and_trigraphs_(programming)[диграфы и триграфы], обрабатываются директивы препроцессора:

* `#define`, `#undef` -- создание и удаление макросов;
* `#include` -- подстановка содержимого файла в данное место;
* `#if`, `#ifdef`, `#ifndef`, `#else`, `#elif`, `#endif` -- обработка различных условий, позволяющая выполнять https://en.wikipedia.org/wiki/Conditional_compilation[условную компиляцию];
* `#pragma` -- выполнить некоторое действие, специфичное для компилятора (или препроцессора);
* и другиие.

Подробно, как работает препроцессор, можно прочитать в https://gcc.gnu.org/onlinedocs/cpp/[документнации].

=== Ассемблирование

=== Компоновка

== Обсуждение терминологии
